#!/usr/bin/env python

import sys
import os
import click

SRC_DIR = os.path.join(os.path.dirname(__file__), "src")
sys.path.append(SRC_DIR)

from core.users import user_entities
from core.users import user_actions
# from core import exceptions


@click.group()
def cli():
    pass


@cli.command()
def runserver():
    """
    Runs the local testing webserver.
    """
    from web.server import runserver
    runserver()


@cli.command()
def sample_data():
    """
    Generate some random data for testing.
    """
    from core.sample_data import SampleData
    sample_data = SampleData()
    sample_data.run()


@cli.command()
@click.argument("user_name", nargs=1, type=click.STRING)
@click.argument("password", nargs=1, type=click.STRING)
@click.argument("full_name", nargs=1, type=click.STRING)
@click.argument("email", nargs=1, type=click.STRING)
def create_user(user_name, password, full_name, email):
    """
    Register a new user in the system.
    """
    user = user_actions.register_new_user(
        user_entities.UserForRegister(
            user_name = user_name,
            clear_password = password,
            full_name = full_name,
            email = email,
        )
    )

    print("Created user {}".format(user.user_name))


if __name__ == "__main__":
    cli()
