#!/usr/bin/env python

import sys
import os
import click

SRC_DIR = os.path.join(os.path.dirname(__file__), "src")
sys.path.append(SRC_DIR)

# from core import actions
# from core import exceptions


@click.group()
def cli():
    pass


@cli.command()
def runserver():
    """
    Runs the local testing webserver.
    """
    from web.server import runserver
    runserver()


if __name__ == "__main__":
    cli()
