ideas = [
    ("Realidad aumentada para lugares históricos", "We're building a powerful crowdfunding marketplace that revolutionizes metrics along powerful engagement methods.", "xavi"),
    ("Proyecto audiovisual para datos de la nasa", "We're building an agile cloud-based ecosystem that leverages bitcoins using accurate hospitality.", "omar"),
    ("Sistema operativo para raspberrypi y otros", "We're building a deep data-driven interface that revolutionizes sales funnels and aggregate fine-dining restaurants.", "omar"),
    ("Piweekr", "xxxxx", "yami / alonso"),
    ("Jugar con la detección de señales de móvil", "We're building a real-time crowdsourced network that revolutionizes sales funnels using impactful fine-dining restaurants.", "alex"),
    ("Machine learning con scalextric", "We're building a disruptive B2B interface that scales metrics through asynchronous tablets.", "mario"),
    ("Plugin de navegador para meter ruido analytics", "We are an authentic machine learning marketplace that maximize ROT using scalable mentorship.", "yami"),
    ("Herramienta de reproducción de pájaros", "We're building an agile B2B platform that disrupts metrics using transparent interest graphs.", "david"),
    ("App para intercambio de datos del seguro", "Basically, we're a powerful mobile-first API that partners microblogging through dynamic 3D motion sensing.", "mario"),
    ("Quotes as a service", "We are a lean e-commerce marketplace that connects small businesses through highly relevant tablets.", "david"),
    ("Micromeetups para desarrolladores", "Basically, we're a semantic big data analytics loyalty platform that disrupts hotels with highly relevant mentorship.", "mario"),
    ("Pack para ciclistas", "We're building a customizable biotech platform that leverages angel investors into aggregate consumers.", "xavi"),
    ("Tiempo fuera del planeta (space weather)", "Basically, we're an aggregate social network that shifts the paradigms of local search through transparent online advertising.", "pabloR"),
    ("Earlybirdaliahunter.io", "We're building a cutting-edge native advertising toolbox that leverages team collaboration through semantic minimum viable products.", "mario"),
    ("Plataforma de audiolibros accesibles", "We're building a scalable e-commerce platform that scales financial projections using dynamic online advertising.", "yami"),
    ("Aplicación para retros distribuidas", "We're building an authentic crowdsourced API that expedites gamification through streamlined pet shops.", "alonso"),
    ("Sistema de asistencia a la tercera edad", "Basically, we're an accurate data-driven application that disrupts venture capital firms along dynamic consumers.", "juanfran"),
    ("Plataforma para que las mamás expliquen conceptos a los niños", "We're building an agile mobile-first application that scales bitcoins and scalable minimum viable products.", "esther"),
    ("Procesado de vídeo en tiempo real (conteo comba)", "Basically, we're an agile marketing automation ecosystem that mobilizes small businesses using impactful non-profits.", "alex"),
    ("Asistencia para mejorar la conducción en silla de ruedas", "Basically, we're a deep mobile network that generates bitcoins with dynamic 3D motion sensing.", "alex"),
    ("Herramienta para (cripto) monedas locales basada en blockchain", "We are an accurate cloud-based application that synchronizes metrics using streamlined non-profits.", "andrés"),
    ("Wikilocos!", "Basically, we're an accurate genome analysis network that transforms sales funnels along personalized hospitality.", "yami"),
    ("Herramienta OSS de time tracking", "Basically, we're an asynchronous mobile-first network that synchronizes hotels using game-changing virality.", "andrey"),
    ("Mind the fraud social network", "we're an open source biotech loyalty platform that leverages content distribution through authentic minimum viable products.", "pabloR"),
    ("Weather prophet para contaminación", "we're a next generation biotech interface that transforms hotels and open source interest graphs.", "yami / marta"),
    ("GraphQl", "We're building an innovative cloud-based application that expedites metrics into asynchronous video messaging.", "alonso"),
    ("Maquetar", "Basically, we're a lean biotech platform that generates hotels into scalable minimum viable products.", "yami"),
    ("Clojure", "Basically, we're an aggregate publishing platform that partners gamification using agile online advertising.", "yami"),
    ("QT", "Basically, we're a transparent mobile-first application that synchronizes microblogging along aggregate minimum viable products.", "xavi"),
    ("Rx", "We're building an agile crowdfunding platform that transforms sales funnels along next generation non-profits.", "alonso"),
    ("Apache Spark", "We're building a lean consumer-based network that generates local search into visual virality.", "mario"),
    ("HTTP2", "We are a real-time data-driven toolbox that partners web marketing using radical online advertising.", "mario"),
    ("Docker", "Basically, we're a next generation biotech API that expedites financial projections along asynchronous online advertising.", "ivan"),
    ("Kubernetes", "We're building an accurate cloud-based API that maximize microblogging into ground-breaking iteration cycles.", "yami"),
    ("TDD...", "We are a powerful big data analytics API that synchronizes venture capital firms with streamlined fine-dining restaurants.", "mario"),
    ("Valut", "We are an asynchronous content-curation toolbox that leverages microblogging along impactful engagement methods.", "anler"),
    ("Rust", "Basically, we're an agile cloud-based application that revolutionizes content distribution with streamlined commercial banking.", "jesus"),
    ("Impresora 3D", "Basically, we're a powerful CMS API that generates team collaboration using open source virality.", "esther"),
    ("Maquetación Android", "Basically, we're an agile content-curation platform that leverages team collaboration using transparent 3D motion sensing.", "xavi"),
    ("Granillo", "We are an agile mobile-first application that disrupts web marketing and dynamic video messaging.", "jesus"),
    ("Purescript", "Basically, we're a premium content-curation network that generates local search through personalized group messaging.", "anler"),
    ("Fregue", "Basically, we're an agile crowdfunding API that revolutionizes ROT with powerful pet shops.", "anler"),
    ("Ethereum + Solidity", "We're building an agile data-driven marketplace that maximize biomedical research and visual virality.", "andrés"),
    ("WebRTC", "Basically, we're an impactful publishing application that generates local search into personalized 3D motion sensing.", "alonso"),
    ("D3", "We are a personalized crowdfunding platform that scales content distribution with open source synergy.", "pablo"),
    ("Arduino", "Basically, we're a disruptive cloud-based loyalty platform that scales venture capital firms along aggregate minimum viable products.", "yami"),
]
