ideas = [
    ("realidad aumentada para lugares históricos", "xxxxx", "xavi"),
    ("proyecto audiovisual para datos de la nasa", "xxxxx", "omar"),
    ("sistema operativo para raspberrypi y otros", "xxxxx", "omar"),
    ("piweekr", "xxxxx", "yami / alonso"),
    ("jugar con la detección de señales de móvil", "xxxxx", "alex"),
    ("machine learning con scalextric", "xxxxx", "mario"),
    ("plugin de navegador para meter ruido analytics", "xxxxx", "yami"),
    ("herramienta de reproducción de pájaros", "xxxxx", "david"),
    ("app para intercambio de datos del seguro", "xxxxx", "mario"),
    ("quotes as a service", "xxxxx", "david"),
    ("micromeetups para desarrolladores", "xxxxx", "mario"),
    ("pack para ciclistas", "xxxxx", "xavi"),
    ("tiempo fuera del planeta (space weather)", "xxxxx", "pabloR"),
    ("Earlybirdaliahunter.io", "xxxxx", "mario"),
    ("plataforma de audiolibros accesibles", "xxxxx", "yami"),
    ("aplicación para retros distribuidas", "xxxxx", "alonso"),
    ("sistema de asistencia a la tercera edad", "xxxxx", "juanfran"),
    ("plataforma para que las mamás expliquen conceptos a los niños", "xxxxx", "esther"),
    ("procesado de vídeo en tiempo real (conteo comba)", "xxxxx", "alex"),
    ("asistencia para mejorar la conducción en silla de ruedas", "xxxxx", "alex"),
    ("herramienta para (cripto) monedas locales basada en blockchain", "xxxxx", "andrés"),
    ("wikilocos!", "xxxxx", "yami"),
    ("herramienta OSS de time tracking", "xxxxx", "andrey"),
    ("mind the fraud social network", "xxxxx", "pabloR"),
    ("weather prophet para contaminación", "xxxxx", "yami / marta"),
    ("GraphQl", "xxxxx", "alonso"),
    ("Maquetar", "xxxxx", "yami"),
    ("Clojure", "xxxxx", "yami"),
    ("QT", "xxxxx", "xavi"),
    ("Rx", "xxxxx", "alonso"),
    ("Apache Spark", "xxxxx", "mario"),
    ("HTTP2", "xxxxx", "mario"),
    ("Docker", "xxxxx", "ivan"),
    ("Kubernetes", "xxxxx", "yami"),
    ("TDD ....", "xxxxx", "mario"),
    ("Valut", "xxxxx", "anler"),
    ("Rust", "xxxxx", "jesus"),
    ("Impresora 3D", "xxxxx", "esther"),
    ("Maquetación Android", "xxxxx", "xavi"),
    ("Granillo", "xxxxx", "jesus"),
    ("Purescript", "xxxxx", "anler"),
    ("Fregue", "xxxxx", "anler"),
    ("Ethereum + Solidity", "xxxxx", "andrés"),
    ("WebRTC", "xxxxx", "alonso"),
    ("d3", "xxxxx", "pablo"),
    ("Arduino", "xxxxx", "yami"),
]
